name = "Preconditioning"
uuid = "55da6227-7db8-4c50-a132-8ba9b4815484"
authors = ["Alexis Montoison <alexis.montoison@polymtl.ca>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "^1.6.0"

[extras]
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Krylov", "Test"]
